FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir python-dotenv==1.0.1 streamlit

# Set environment variables if needed
ENV PYTHONUNBUFFERED=1

# Expose Streamlit port
EXPOSE 8501

COPY streamlit_app.py .
COPY .env .
COPY langgraph.json .

# Run Streamlit
CMD ["streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0"]
